<?
//////////////////////////////////////
//
// the value to the right of => maps the product type/id being posted by Cisco to a SKU in our system
//
//////////////////////////////////////

	$ciscoArray = array(
					"Content Networking" => array(
						358 => 0,//	Catalyst 65XX (such as 6509, 6513) Layer 3 switches	.
						274 => 0,//	Content Distribution	.
						275 => 0,//	Content Filtering	.
						276 => 0,//	Content Management	.
						202 => 0,//	Content Providers	.
						201 => 0,//	E-Learning Applications	.
						757 => 0,//	Other	.
						756 => 0,//	Stream Serving	.
						355 => 0//	Video Networking	.
					),
					"IOS Software" => array(
						681 => 0,//	Application Based Routing	.
						682 => 0,//	Billing / Prepaid Billing	.
						685 => 0,//	iEdge	.
						683 => 0,//	IP Mobility	.
						686 => 0,//	MPLS	.
						751 => 0,//	Other	.
						684 => 0//	Performance Management, Monitoring, and Reporting	.
					),
					"IP Communications" => array(
						397 => 37,//	Accounting/Billing 37
						399 => 37,//	Application Servers	37
						402 => 37,//	Contact Center	37
						401 => 39,//	Contact Center Applications	39
						403 => 39,//	Customer Relationship Management	39
						404 => 39,//	E-Conferencing and E-Collaboration	39
						407 => 45,//	IP Phone Applications	45
						409 => 39,//	Messaging Applications	39
						411 => 41,//	Operations, Administration & Management (OAM)	41
						430 => 37,//	Other	37
						413 => 39,//	Personnel and Personal Management/Productivity	39
						508 => 37,//	Platform/Remote Agents	37
						415 => 39,//	Rich Media Recording	39
						417 => 37,//	Solution Enablers	37
						419 => 41,//	Test Tools	41
						422 => 39,//	Unified Messaging/Voice Mail	39
						428 => 39,//	Video Communications	39
						514 => 39,//	Voice Endpoints - Operator Consoles	39
						513 => 39,//	Voice Endpoints - Soft Phones	39
						424 => 39,//	Voice Endpoints - Wired	39
						512 => 39//	Voice Endpoints - Wireless	39
					),
					"IP Communications - Service Provider" => array(
						725 => 0,//	Announcement Server	.
						726 => 0,//	Automated Speech Recognition and Text to Speech (ASR/TTS)	.
						727 => 0,//	Billing	.
						728 => 0,//	CALEA	.
						729 => 0,//	Call Accounting	.
						730 => 0,//	Conferencing	.
						731 => 0,//	Enhanced Services Platform Call Blocking	.
						732 => 0,//	Hosted IP Telephony	.
						733 => 0,//	Line Side/Access	.
						734 => 0,//	Media Server	.
						735 => 0,//	Mediation	.
						736 => 0,//	Multiservice VPN	.
						750 => 0,//	Other	.
						737 => 0,//	Performance Management	.
						738 => 0,//	Router Server	.
						755 => 0,//	Security	.
						739 => 0,//	Transit Wireless	.
						740 => 0,//	Transit Wireline	.
						741 => 0,//	Unified Communications	.
					),
					"Mobile Wireless" => array(
						711 => 0,//	Location Based Services	.
						712 => 0,//	Mediation	.
						713 => 0,//	Messaging	.
						714 => 0,//	Mobile Applications	.
						715 => 0,//	Network Access/Transactions	.
						716 => 0,//	Network Service Control	.
						717 => 0,//	Other Mobile Wireless Solutions	.
						718 => 0,//	Public Wireless LAN	.
						719 => 0,//	Rich Media	.
						710 => 0,//	Signaling Transport and Signaling over IP (SS7overIP)	.
						720 => 0,//	Wireless IP Transport/Security/Optimization	.
						721 => 0,//	Wireless Solutions	.
					),
					"Network and Service Management" => array(
						515 => 0,//	Accounting & Billing	.
						516 => 0,//	Broadband Access & IP Services	.
						517 => 0,//	Campus	.
						27 => 0,//	CiscoWorks2000 CIM-XML Data Exchange	.
						24 => 0,//CiscoWorks2000 Desktop Integration	.
						137 => 0,//	CiscoWorks2000 Fault Management Integration	.
						25 => 0,//	CiscoWorks2000 NMS Integration	.
						26 => 0,//	CiscoWorks2000 Service Management Data Exchange	.
						518 => 0,//	Configuration & Provisioning	.
						519 => 0,//	Data Center	.
						520 => 0,//	Device Instrumentation	.
						521 => 0,//	Device Management	.
						522 => 0,//	Fault Management	.
						523 => 0,//	IP Telephony	.
						524 => 0,//	Mobile Wireless	.
						222 => 0,//	Other	.
						525 => 0,//	Performance Management	.
						526 => 0,//	Routing and Switching	.
						527 => 0,//	Security Management	.
						528 => 0//	Wireless	.
					),
					"Radio Frequency Identification" => array(
						804 => 0,//	Application and Software	.
						805 => 0,//	Management	.
						803 => 0,//	Middleware	.
						802 => 47//	Reader/Printer Client	47
					),
					"Security and VPN" => array(
						104 => 6,//	Application Security	6
						101 => 8,//	Identity	8
						288 => 0,//	Other	.
						102 => 12,//	Perimeter Security	12
						103 => 14,//	Secure Connectivity	14
						105 => 16,//	Security Management and Monitoring	16
						143 => 0,//	Services: Application and Code Review Services	.
						139 => 0,//	Services: Design and Implementation Services	.
						146 => 0,//	Services: Incident Response Services	.
						145 => 0,//	Services: Outsourced Monitoring and Management Services	.
						140 => 0,//	Services: Policy and Procedures Services	.
						141 => 0,//	Services: Vulnerability Assessment Services	.
						356 => 0//	Video Networking	.
					),
					"Storage Networking" => array(
						223 => 0,//	Network Interface Cards	.
						352 => 0,//	Other	.
						224 => 0,//	Storage Networking Hardware 	.
						163 => 0,//	Storage Networking Services	.
						160 => 0,//	Storage Networking Software	.
						162 => 0,//	Storage over Metro Optical	.
						161 => 0,//	Storage over WAN	.
						164 => 0//	Storage Service Providers	.
					),
					"Wireless Networking" => array(
						680 => 5,//	Location Based Service	5
						353 => 5,//	Other	5
						296 => 5,//	Wireless Client Devices	5
						297 => 5,//	Wireless Integrated Applications	5
						298 => 5//	Wireless Management and Tools	5
					)
	);
/*
	$ciscoArray = array(
					"Content Networking" => array(
												205 => "Cisco Cache Engine Series",
												206 => "Cisco Content Distribution Manager (CDM)",
												207 => "Cisco Content Engine (CE)",
												280 => "Cisco Content Transformation Engine (CTE)",
												203 => "Cisco CSS 11000 Series Content Services Switches",
												208 => "Cisco IP/TV 3400 Video Servers",
												386 => "Cisco IPCC Express",
												204 => "Other"
					),

					"IOS Software" => array (
												687 => "Cisco IOS Software Releases 11.0",
												688 => "Cisco IOS Software Releases 11.1",
												689 => "Cisco IOS Software Releases 11.2",
												690 => "Cisco IOS Software Releases 11.3",
												695 => "Cisco IOS Software Releases 12.0 Mainline",
												693 => "Cisco IOS Software Releases 12.0 S",
												691 => "Cisco IOS Software Releases 12.0 Special and Early Deployments",
												692 => "Cisco IOS Software Releases 12.0 ST",
												694 => "Cisco IOS Software Releases 12.0 T",
												697 => "Cisco IOS Software Releases 12.1 E",
												699 => "Cisco IOS Software Releases 12.1 Mainline",
												696 => "Cisco IOS Software Releases 12.1 Special and Early Deployments",
												698 => "Cisco IOS Software Releases 12.1 T",
												703 => "Cisco IOS Software Releases 12.2 Mainline",
												700 => "Cisco IOS Software Releases 12.2 S",
												701 => "Cisco IOS Software Releases 12.2 Special and Early Deployments",
												702 => "Cisco IOS Software Releases 12.2 T",
												706 => "Cisco IOS Software Releases 12.3 Mainline",
												704 => "Cisco IOS Software Releases 12.3 Special and Early Deployments",
												705 => "Cisco IOS Software Releases 12.3 T",
												707 => "Other"
					),

					"IP Communications" => array (
												398 => "Catalyst 65XX Layer 3 Switches",
												400 => "Cisco 7500 Series Routers",
												405 => "Cisco 7600 Series Routers",
												406 => "Cisco Access Switches",
												//408 => "Cisco CallManager 2.4-ICS",
												410 => "Cisco CallManager 2.4-MCS",
												412 => "Cisco CallManager 3.0(1)-MCS",
												414 => "Cisco CallManager 3.0(10)-MCS",
												416 => "Cisco CallManager 3.0(11)-MCS",
												418 => "Cisco CallManager 3.0(12)-MCS",
												//420 => "Cisco CallManager 3.0(2d)-ICS",
												421 => "Cisco CallManager 3.0(2d)-MCS",
												423 => "Cisco CallManager 3.0(3)-MCS",
												425 => "Cisco CallManager 3.0(4)-MCS",
												426 => "Cisco CallManager 3.0(5)-MCS",
												427 => "Cisco CallManager 3.0(6)-MCS",
												429 => "Cisco CallManager 3.0(7)-MCS",
												//431 => "Cisco CallManager 3.0(8)-ICS",
												432 => "Cisco CallManager 3.0(8)-MCS",
												433 => "Cisco CallManager 3.0(9)-MCS",
												434 => "Cisco CallManager 3.1(1)-MCS",
												//435 => "Cisco CallManager 3.1(2)-ICS",
												436 => "Cisco CallManager 3.1(2)-MCS",
												//437 => "Cisco CallManager 3.1(3)-ICS",
												438 => "Cisco CallManager 3.1(3)-MCS",
												//439 => "Cisco CallManager 3.1(3a)-ICS",
												440 => "Cisco CallManager 3.1(3a)-MCS",
												441 => "Cisco CallManager 3.1(4a)-MCS",
												442 => "Cisco CallManager 3.1(4b)-MCS",
												//443 => "Cisco CallManager 3.2(1)-ICS",
												444 => "Cisco CallManager 3.2(1)-MCS",
												//464 => "Cisco CallManager 3.2(2)-ICS",
												466 => "Cisco CallManager 3.2(2)-MCS",
												468 => "Cisco CallManager 3.2(2a)-MCS",
												470 => "Cisco CallManager 3.3(2)spA-MCS",
												678 => "Cisco CallManager 4.0(2)",
												679 => "Cisco CallManager 4.1(2)",
												819 => "Cisco CallManager Express 3.2",
												471 => "Cisco Collaboration Server (CCS)",
												472 => "Cisco Computer Telephony Integration (CTI)",
												474 => "Cisco Distribution Switches: 3548XL",
												476 => "Cisco Distribution Switches: 36XX Series",
												478 => "Cisco Distribution Switches: 4XXX Series",
												479 => "Cisco eMail Manager (CEM)",
												480 => "Cisco Intelligent Contact Management (ICM)",
												482 => "Cisco IP Contact Center (IPCC) via Cisco ICM CTI Server",
												484 => "Cisco IP Phone 7900 Series",
												486 => "Cisco IP/VC 3520 Gateway v2.2",
												487 => "Cisco IP/VC 3525 Gateway v2.2",
												488 => "Cisco IP/VC 3530 Video Terminal Adapter",
												489 => "Cisco IP/VC 3540 Multipoint Control Unit (MCU) v1.0",
												490 => "Cisco MDS-based storage products",
												491 => "Cisco Multimedia Conference Manager 12.1(5)XM3",
												492 => "Cisco PIX Firewall",
												676 => "Cisco Unity",
												677 => "Cisco Unity Bridge",
												493 => "IP/VC 3510 Multipoint Control Unit (MCU) v2.2",
												494 => "Linksys Products",
												495 => "Other"
					),

					"IP Communications - Service Provider" => array (
												743 => "Cisco AS5350 Universal Gateway",
												744 => "Cisco AS5400 Universal Gateway",
												745 => "Cisco AS5850 Universal Gateway",
												742 => "Cisco BTS 10200 Softswitch",
												746 => "Cisco MGX 8880 Media Gateway",
												747 => "Other"
					),

					"Mobile Wireless" => array (
												722 => "IP Transfer Point (ITP)",
												752 => "Other"
					),

					"Network and Service Management" => array (
												601 => "Cisco 10000 Manager",
												602 => "Cisco 12000/10720 Router Manager",
												603 => "Cisco 7000 Series Manager",
												604 => "Cisco 7600 Router Manager",
												605 => "Cisco Access Point Name Manager",
												606 => "Cisco Access Router Manager",
												569 => "Cisco Broadband Access Center for Broadband Aggregation",
												570 => "Cisco Broadband Access Center for Cable",
												571 => "Cisco Broadband Access Center for CNSP",
												572 => "Cisco Broadband Access Center for ETTx",
												607 => "Cisco Broadband Configurator",
												608 => "Cisco Broadband Operating System",
												609 => "Cisco Broadband Troubleshooter",
												597 => "Cisco Building Broadband Service Manager (BBSM)",
												610 => "Cisco Cable Diagnostic Manager",
												579 => "Cisco Cable Manager",
												611 => "Cisco Cable Troubleshooter Software",
												612 => "Cisco Catalyst 8500 Manager",
												580 => "Cisco Catalyst Switch Manager",
												563 => "Cisco CNS 2100 Series Intelligence Engine",
												558 => "Cisco CNS Access Registrar",
												613 => "Cisco CNS Access Registrar Identity Cache Engine",
												559 => "Cisco CNS Address and Name Registrar",
												560 => "Cisco CNS Configuration Engine",
												561 => "Cisco CNS HLR Proxy Server",
												564 => "Cisco CNS Netflow Collection Engine",
												565 => "Cisco CNS Network Registrar",
												566 => "Cisco CNS Notification Engine",
												614 => "Cisco CNS Performance Engine",
												615 => "Cisco CNS SDK",
												567 => "Cisco CNS Subscriber Edge Services Manager",
												616 => "Cisco CPE Commander",
												581 => "Cisco DSL Manager",
												617 => "Cisco Element Manager System",
												618 => "Cisco Embedded Device Manager",
												619 => "Cisco Extensible Provisioning and Operations Manager",
												596 => "Cisco Info Center",
												620 => "Cisco Info Center for Security Monitoring",
												621 => "Cisco Info Center VPN Policy Manager",
												574 => "Cisco IP Solution Center",
												622 => "Cisco IP Solution Center L2 VPN Management",
												623 => "Cisco IP Solution Center MPLS VPN Management",
												624 => "Cisco IP Solution Center Security Management",
												583 => "Cisco Media Gateway control Node Manager",
												582 => "Cisco Media Gateway Manager",
												625 => "Cisco Mobile Wireless Center",
												626 => "Cisco Mobile Wireless Fault Mediator",
												575 => "Cisco MPLS Tunnel Builder",
												627 => "Cisco MPLS Tunnel Builder Pro",
												628 => "Cisco Network Analysis Module Software",
												629 => "Cisco Network Analysis Toolkit",
												630 => "Cisco Network Assistant",
												598 => "Cisco Network Connectivity Center",
												631 => "Cisco Network Connectivity Center Application Service Manager",
												632 => "Cisco Network Connectivity Center Business Dashboard",
												633 => "Cisco Network Connectivity Center Business Impact Manager",
												634 => "Cisco Network Connectivity Center MPLS Manager",
												635 => "Cisco Network Connectivity Center Routing Protocol Services Manager",
												636 => "Cisco Network Connectivity Monitor",
												637 => "Cisco Network Data Analyzer",
												639 => "Cisco Optimized Edge Routing Master Controller Engine",
												576 => "Cisco Packet Telephony Center Monitoring and Troubleshooting",
												640 => "Cisco Packet Telephony Center Virtual Switch",
												641 => "Cisco Provisioning Center",
												600 => "Cisco Resource Policy Management System",
												554 => "Cisco Secure Access Control Server for Unix",
												642 => "Cisco Secure Access Control Server for Windows",
												643 => "Cisco Secure Access Control Server Solution Engine",
												556 => "Cisco Secure User Registration Tool",
												644 => "Cisco Subscriber Registration Center Device Provisioning Registrar",
												585 => "Cisco Transport Manager",
												645 => "Cisco Universal Gateway Call Analyzer",
												584 => "Cisco Universal Gateway Manager",
												646 => "Cisco Voice Services Provisioning Tool",
												647 => "Cisco VPN Solution Center",
												648 => "Cisco WAN Access Performance Management System",
												649 => "Cisco WAN Manager",
												650 => "CiscoRemote",
												651 => "CiscoWorks Access Control List Manager",
												652 => "CiscoWorks Auto Update Server Software",
												653 => "CiscoWorks Blue Internetwork Status Monitor",
												654 => "CiscoWorks Campus Manager",
												655 => "CiscoWorks CiscoView",
												656 => "CiscoWorks Common Services Software",
												657 => "CiscoWorks Device Fault Manager",
												658 => "CiscoWorks Ethernet Subscriber Solution Engine",
												659 => "CiscoWorks Fault History",
												660 => "CiscoWorks for Mobile Wireless",
												661 => "CiscoWorks Gateway Statistics Utility",
												542 => "CiscoWorks Hosting Solution Engine",
												662 => "CiscoWorks Internetwork Performance Monitor",
												663 => "CiscoWorks IP Phone Help Desk Utility",
												664 => "CiscoWorks IP Phone Information Utility",
												543 => "CiscoWorks IP Telephony Environment Monitor",
												665 => "CiscoWorks IP Telephony Monitor",
												544 => "CiscoWorks LAN Management Solution",
												666 => "CiscoWorks Management Center for Cisco Security Agents",
												667 => "CiscoWorks Management Center for Firewalls",
												668 => "CiscoWorks Management Center for IDS Sensors",
												669 => "CiscoWorks Management Center for VPN Routers",
												670 => "CiscoWorks Monitoring Center for Performance",
												671 => "CiscoWorks Monitoring Center for Security",
												546 => "CiscoWorks QoS Policy Manager",
												672 => "CiscoWorks Resource Manager Essentials",
												547 => "CiscoWorks Routed WAN Management Solution",
												673 => "CiscoWorks Security Information Management Solution",
												549 => "CiscoWorks Small Network Management Solution",
												551 => "CiscoWorks Voice Manager",
												674 => "CiscoWorks VPN Monitor",
												550 => "CiscoWorks VPN/Security Management Solution",
												553 => "CiscoWorks Wireless LAN Solution Engine",
												28 => "CiscoWorks2000",
												158 => "CiscoWorks2000 Device Fault Manager v1.0",
												29 => "CiscoWorks2000 LAN Management Solution",
												30 => "CiscoWorks2000 Routed WAN Management Solution",
												31 => "CiscoWorks2000 Service Management Solution",
												675 => "nGenius Real-Time Monitor",
												159 => "Other"
					),

					"Radio Frequency Identification" => array (
												806 => "CISCO CATALYST 2950 SERIES SWITCHES",
												807 => "CISCO CATALYST 2970 SERIES SWITCHES",
												808 => "CISCO CATALYST 3550 SERIES SWITCHES",
												809 => "CISCO CATALYST 3560 SERIES SWITCHES",
												810 => "CISCO CATALYST 3750 SERIES SWITCHES",
												811 => "Other"
					),

					"Security and VPN" => array (
												395 => "Catalyst 6000 Series Switch",
												510 => "Catalyst 6500 Series Switch",
												127 => "Cisco 1700 series routers",
												124 => "Cisco 2600 series routers",
												126 => "Cisco 3600 series routers",
												123 => "Cisco 7100 VPN series router",
												391 => "Cisco 7300  VPN series router",
												392 => "Cisco Catalyst 6500 Series IDS Module (IDSM-2)",
												509 => "Cisco Catalyst 6500 with VPN Service Module (VPNSM",
												511 => "Cisco Content Engine",
												131 => "Cisco IOS Firewall",
												132 => "Cisco PIX 500 Firewall",
												128 => "Cisco Secure Access Control Server",
												120 => "Cisco Secure VPN Client",
												387 => "Cisco Security Agent (CSA)",
												119 => "Cisco VPN 3000 Concentrator",
												394 => "CiscoWorks  VPN/Security Management SolutionCiscoWorks VPN/Security Management Solution(VMS)",
												389 => "CiscoWorks-SIMS",
												393 => "Firewall Services Module for Cisco Catalyst. 6500 Series and Cisco 7600 Series",
												263 => "Firewall: Managed Firewall based on Cisco IOS Router",
												262 => "Firewall: Managed Firewall based on Cisco PIX Firewall",
												388 => "HIDS: Host-Based Intrusion Detection",
												270 => "IDS: Managed Cisco Host IDS",
												271 => "IDS: Managed IDS based on Cisco IDS Appliance",
												272	=> "IDS: Managed IDS based on Cisco IOS Router",
												273	=> "IDS: Managed IDS based on Cisco PIX Firewall",
												390 => "NIDS: Network-based Intrusion Detection Sensors",
												265 => "VPN: Managed RAS VPN based on Cisco IOS Router",
												264 => "VPN: Managed RAS VPN based on Cisco VPN 3000 Series Concentrator",
												268 => "VPN: Managed site-to-site VPN based on Cisco IOS Router",
												269 => "VPN: Managed site-to-site VPN based on Cisco PIX Firewall",
												267 => "VPN: Managed site-to-site VPN based on Cisco VPN 3000 Series Concentrator"
					),
					
					"Storage Networking" => array (
												181 => "Cisco MDS 9200",
												191 => "Cisco MDS 9500",
												176 => "Cisco ONS 15200 Series",
												177 => "Cisco ONS 15454 Series",
												200 => "Cisco ONS 15530",
												174 => "Cisco ONS 15540 ESP",
												192 => "Cisco SN 5428 Storage Router",
												279 => "Other"
					),

					"Wireless Networking" => array (
												301 => "Cisco Aironet 1100 Access Points",
												300 => "Cisco Aironet 1200 Access Points",
												302 => "Cisco Secure Access Control Server",
												321 => "Other"
					)
	);
*/
?>
