/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Mytest5.xs. Do not edit this file, edit Mytest5.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Mytest5.xs"
#include <sys/vfs.h>
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


#line 19 "Mytest5.c"

XS(XS_Mytest5_statfs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest5_statfs)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mytest5::statfs(path)");
    SP -= items;
    {
	char*	path = (char *)SvPV_nolen(ST(0));
#line 15 "Mytest5.xs"
	int i;
	struct statfs buf;
#line 33 "Mytest5.c"
#line 18 "Mytest5.xs"
	i = statfs(path, &buf);
	if (i==0) {

			XPUSHs(sv_2mortal(newSVnv(buf.f_bavail)));
			XPUSHs(sv_2mortal(newSVnv(buf.f_bfree)));
			XPUSHs(sv_2mortal(newSVnv(buf.f_blocks)));
			XPUSHs(sv_2mortal(newSVnv(buf.f_bsize)));
			XPUSHs(sv_2mortal(newSVnv(buf.f_ffree)));
			XPUSHs(sv_2mortal(newSVnv(buf.f_files)));
			XPUSHs(sv_2mortal(newSVnv(buf.f_type)));
	} else {
		XPUSHs(sv_2mortal(newSVnv(errno)));	
	}
#line 48 "Mytest5.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Mytest5); /* prototype to pass -Wmissing-prototypes */
XS(boot_Mytest5)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Mytest5::statfs", XS_Mytest5_statfs, file);
    XSRETURN_YES;
}

