#!/tools/bin/perl

=head NAME
compress_stress

=head1 DESCRIPTION

=cut
=head1 bugs
=cut

=head1 Authors
Dong Duong 
7/13/05
run Iperf selectively by choosing the files located in /tools/files/ordered_files
=cut 

use lib '/tools/lib/perl5/site_perl/5.8.4';
use lib '/tools/tests/regression';
use Test::More  qw(no_plan); 
use Time::localtime;  
use Carp ;
use Getopt::Std ;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_rpc;
my $client36 ='10.200.38.36';
my $client37 ='10.200.38.37';
my $client38 ='10.200.38.38';
my $server76 ='30.30.20.76';
my $server78 ='30.30.20.78';
my $server79 ='30.30.20.79';

my $sess = 10;
my $testcase="compress_stress";
my $duration = 9999;
my $directory = '/tools/files/ordered_files';
run_iperfs ($client36, $server76, $sess) ;
run_iperfs ($client38, $server78, $sess) ;
print "\nALL TESTS SHOULD BE RUNNING ....\n";

#*************************************************************************
sub run_iperfs
{
    my $client = shift ;
    my $server = shift;
    my $sess = shift;
    my $duration = shift ;
    my $pass = FAIL;
    my $test = "/tools/tests/dong/iperfc_file_loop $server $sess > /dev/null ";
    print "Test $client $server \n";
    print  "Invoke: $test \n";
    my $result = `ssh $client $test`;

}
=head1 COPYRIGHT
Copyright (c) 2005, Author(s). All rights reserved.
This module is the property of Orbital Data Corporation.
It may not be used or modified by anyone without express permission
of Orbital Data Corporation.
=cut
