#!/tools/bin/perl -w
use strict;
my $dir = '/orb_patches/';
my $bot = '10.200.2.103';
#my $res = `ls -rtl /orb_patches/ |grep 0.0.0.| tail -1`;
#my $res = `/tools/tests/regression/ssh_bsd.exp $bot /var/ftp/patches |grep 0.0.0.| tail -1`;
my $res = `lftp -c 'open $bot/patches\; ls -rt | grep 0.0.0. | tail -1\; bye'`; 
my @res = split(/\s+/, $res);
my $file_name = pop(@res);
print "TESTED PATCH IS: $file_name\n";
my $url = "ftp://"."$bot"."/patches/";
#print "\nURL is $url \n";
my $download_result = &run_wget($url, $file_name);
if ($download_result =~ /Remote file no newer than local file/) {
   print "NO BUILD TODAY\n"; exit 1;
   } else {
      print "MOVE THE PATCH TO $dir\n", `mv $file_name $dir`;
      print "START REGRESSION ON $file_name \n"
   }

my $file = "$dir"."$file_name";
#print "\nDIR ", `ls $file`;
#print "\n MFILE is ", -M $file;
#if ((0.01 < (-M $file)) && ((-M $file) < 1)) { print "\ntake this file\n";}
#   else {print"\nthis is an old file \n";}

#----------------------------------------------------
sub run_wget
  {
  my $url = shift ;
  my $file = shift ;
  $url .= "$file" ;
  print "URL($url)\n";
  my $wget = `wget $url -N 2>&1`;
  print "$wget \n";
  return $wget ;
}



