#!/tools/bin/perl -w 

use Test::More  tests => 2 ; # the number of tests
use Carp;
use strict;
use Time::localtime;
my $testcase = 'pod4_regress';
my $local_orb = 10.104.1.3;
my $rem_server = 10.104.2.2;
my $tm=localtime;
$tm = sprintf("%02d%02d%04d", $tm->mday,($tm->mon)+1, $tm->year+1900);

my $log_file = "\/logs\/TestResult\/"."$testcase"."_$tm".".log";
   open (LOG,  "> $log_file") || die "Could not open the file $log_file \n";

#is (run_test('/tools/tests/dong/performance_reg -o 20.20.20.50 -s 30.30.20.76 -c 1',$log_file), 1, "IPerf Performance Regression");
#is (run_test('/tools/tests/dong/ab.pl -o 20.20.20.50 -s 30.30.20.76',$log_file), 1, "Apache Benchmark Regression");

if (run_test('/tools/tests/dong/performance.pl -o 10.104.1.3 -s 10.104.2.2 -c 1',$log_file)) {
   print LOG  "\nIPerf Performance Regression:  PASS \n"
   } else { print LOG  "\nIPerf Performance Regression:  FAIL \n"}
   print LOG '*' x80, "\n\n";
if (run_test('/tools/tests/dong/apache.pl -o 10.104.1.3 -s 10.104.2.2', $log_file)) {
   print LOG  "\nApache Benchmark Regression:  PASS \n"
   } else { print LOG  "\nApache Benchmark Regression:  FAIL \n"}
   print LOG '*' x80, "\n\n";

#print `mail \-s \"Regression Test Results\" dong\@orbitaldata.com \< $log_file`; 
print `mail \-s \"Regression Test Results\" regression-list \< $log_file`; 

#*******************************************************************************
sub run_test
{
    my $test = shift ;
    my $log_file = shift;
    my $case_pass = 0;        #set result to FAIL by default;
    my $case_fail = 0;
    open (LOG,  ">> $log_file") || die "Could not open the file $log_file \n";
    my $invoke = "/tools/bin/perl $test" ;
    print "\nRunning:  $invoke \n" ;
    print LOG "\nRunning: $invoke \n";
    sleep 2 ;
    my @result = `$invoke` ;
    my $i = 0;
    while ($result[$i]) {
      if ($result[$i]=~ /not ok\s/) {
         print LOG "Sub-Case $result[$i]";
         $case_fail++;
#         print "\nTotal cases fail: $case_fail \n";
         } elsif ($result[$i] =~ /ok\s/) {
             print LOG  "Sub-Case $result[$i]\n";
             $case_pass++;      #test fails because at least one sub-case fails.
#             print "\nTotal cases pass: $case_pass \n";
             }
      $i++;
    }  #end of while, means all sub-cases pass!
    
    if ($case_fail) {                
        print LOG "\nTest Failed!!! \n";
        print LOG "Check the logs of individual testcase for more details.\n";
        }   

    print "Total sub-cases PASS: $case_pass \n";
    print "Total sub-cases FAIL: $case_fail \n";
    return $case_pass ;
}


