#!/bin/sh
if [ $# -ne 2 ]; then
   echo "usage $0 <IPERF Server> <#sess>"
   exit 1
fi
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/1 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/2 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/3 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/4 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/5 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/6 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/7 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/8 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/9 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/10 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/11 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/12 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/13 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/14 &
/tools/tests/dong/iperfc_file $1 $2 99999 /dbc1/15 &
