/*
 * Created on May 12, 2005
 * Chance Williams
 */
package com.keylabs.monitoring.rc;

import org.w3c.dom.Document;

import com.keylabs.monitoring.ExternalProgramExecutor;
import com.keylabs.monitoring.FileIO;
import com.keylabs.monitoring.MyXMLParser;
import com.keylabs.monitoring.TimeCollection;

public final class RCOutput {

     public static void launchRCTracking(String strLocationToWriteResults) throws Exception {


        //GET CONFIG DATA FROM XML
        Document doc = MyXMLParser.parseXmlFile("NodeConfig.xml"); // it will parse the NodeConfig.xml and store the contents into a document object
        String strExternalProgram = MyXMLParser.getElementAttr_ReturnValue(doc, "RCOutput", "ExternalProgram"); // it will get the values for ProcsToWatchFor, TempFile and ExternalProgram
        String strTempFile = MyXMLParser.getElementAttr_ReturnValue(doc, "RCOutput", "TempFile");
        String strDateTime = TimeCollection.getDateTimeStamp();
        String strOutputPath = MyXMLParser.getElementAttr_ReturnValue(doc, "RCOutput", "OutputPath");
        // String strLocationToWriteResults = MyXMLParser.getElementAttr_ReturnValue(doc, "RCOutput", "OutputFile");
        
        ExternalProgramExecutor.executeProgram(strExternalProgram, "", true);  //it will execute the exeternal program (perl scripts) and get the system statistics then stored it into a temporary file

        String strRC = FileIO.ReadFileFromDisk(new StringBuilder().append(strOutputPath).append(strTempFile).toString()); // it will read the tempfile generated by the perlscript and convert it into string 
   
        // FileIO.writeStringToFile(strOutputPath + strLocationToWriteResults, strDateTime + "," + strRC + "\n", true);

           pw.println( "RCOutput,"+addr.getHostName()+ "," + strDateTime + "," + strRC +"\n"); // it will send to the server from local machine
    }


}//END OF CLASS



