
SELECT  A.BRANCH_IRID 
         FROM JR_COMMON.I$SDD_TRANS_BRANCH_MATRIX  A , JR_COMMON.I$SDD_BRANCHES B  ,
              JR_COMMON.I$SDD_TRANSACTIONS C , JR_COMMON.I$SDD_PRODUCTS D 
        WHERE C.NAME = 'mthaha_democheck_txn9'
          AND A.TRANSACTION_IRID = C.IRID 
          AND A.BRANCH_IRID      = B.IRID 
          AND B.PRODUCT_IRID     = D.IRID 
        ORDER BY D.NAME ;

SELECT BASED_ON_CONFIG_IRID FROM JR_COMMON.I$SDD_TRANSACTIONS A 
WHERE A.NAME = 'mthaha_democheck_txn9';


SELECT C.NAME, C.IRID , A.BRANCH_IRID , D.NAME
    FROM JR_COMMON.I$SDD_TRANS_BRANCH_MATRIX  A , JR_COMMON.I$SDD_BRANCHES B  ,
              JR_COMMON.I$SDD_TRANSACTIONS C , JR_COMMON.I$SDD_PRODUCTS D 
        WHERE A.TRANSACTION_IRID = HEXTORAW('5D4748A4C7A7909EE0401490C2CF55B9')
          AND A.TRANSACTION_IRID = C.IRID 
          AND A.BRANCH_IRID      = B.IRID 
          AND B.PRODUCT_IRID     = D.IRID 
        ORDER BY D.NAME ;
SELECT NAME FROM JR_COMMON.I$SDD_BRANCHES WHERE IRID IN (
  SELECT BRANCH_IRID FROM JR_COMMON.I$SDD_TRANS_BRANCH_MATRIX WHERE TRANSACTION_IRID = HEXTORAW('5D4748A4C7A7909EE0401490C2CF55B9')
  );

-- GET THE LABEL NAME ON WHICH TXN IS CREATED
  SELECT IRID, NAME, DATE_CREATED FROM JR_COMMON.I$SDD_CONFIGURATIONS WHERE IRID = HEXTORAW('5D2EFD7D0987B478E0401490BFCF0616');

-- IF THE CONFIG SPEC IS .S GET THE CLOSEST CONFIG IRID 
SELECT IRID, NAME, DATE_CREATED FROM   JR_COMMON.I$SDD_CONFIGURATIONS c
               WHERE  c.NAME like  'FUSIONAPPS_MAIN_LINUX%'
               AND    c.NAME not like  'FUSIONAPPS_MAIN_LINUX%.S'
               AND DATE_CREATED < '3-DEC-08';
               AND rownum < 2
               ORDER BY c.DATE_CREATED ASC ;
