/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Mytest2.xs. Do not edit this file, edit Mytest2.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Mytest2.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


#line 18 "Mytest2.c"

XS(XS_Mytest2_is_even); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest2_is_even)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mytest2::is_even(input)");
    {
	int	input = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 14 "Mytest2.xs"
	RETVAL = (input%2 == 0);
#line 32 "Mytest2.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Mytest2); /* prototype to pass -Wmissing-prototypes */
XS(boot_Mytest2)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Mytest2::is_even", XS_Mytest2_is_even, file);
    XSRETURN_YES;
}

