#!/tools/bin/perl
=head1 Authors
Dong Duong 
toggle compression to clearout its history
=cut 

use lib '/tools/lib/perl5/site_perl/5.8.4';
use Time::localtime;  
use Carp ;
use Getopt::Std ;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_rpc;


my $testcase="reset_comp";

#Require @least 2 inputs: the tested ORB and the IPERF Server.
getopt ("o") ;

if ( ! $opt_o) {
  print "Usage: $testcase  -o <OrbIP>  \n" ;
  exit 1 ;}
my $orb = $opt_o; chomp ($orb);       #setup the Orb for XMLRPC
my $url = "http://$orb:2050/RPC2";
my $rpc = Orbital::Rpc->new($url);

# Get the system's current compression setting
 print "Enable Compression ", $rpc->set_parameter('Compression.EnableCompression', '1'), "\n";
 print "Disable Compression ", $rpc->set_parameter('Compression.EnableCompression', '0'), "\n";
 print "Enable Compression ", $rpc->set_parameter('Compression.EnableCompression', '1'), "\n";
