#!/usr/bin/perl -w
 
use FindBin;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_constants;
use orbital_rpc;
use Getopt::Std; 
#
# Initialization code
#
my $orb = "10.200.38.63" ;
getopt("o");
if ($opt_o) {$orb=$opt_o; chomp($orb)}
my $Rpc = Orbital::Rpc->new("http://$orb:2050/RPC2");
#my $Rpc = Orbital::Rpc->new('http://localhost:2050/RPC2');
sleep 3;
print "Test started.\n";
   #
   # If there was an Alert, display it
   #
   (my $NumAlerts, my @Alerts) = $Rpc->get_alerts();
      print("Displaying Alert!\n");
      print" @Alerts \n";
 
   my $MaxAllowedThroughput = $Rpc->get_throughput();
   print "MAX THROUGHPUT: $MaxAllowedThroughput \n";
   my $IsPassthrough = $Rpc->get_parameter("PassThrough");
   print("PassThrough: $IsPassthrough\n");
   
#  $IsPassthrough = $Rpc->get_parameter("COMPRESSION.COMPUTECHECKSUM");
#   print("COMPRESSION.COMPUTECHECKSUM: $IsPassthrough\n");

   my $Version = $Rpc->get_system_variable("Version");
   print "VERSION-1 $Version \n";

   my $Primary_lic_stat = $Rpc->get_system_variable("PrimaryLicenseFileStatus");
   print "Pri_lic_stat $Primary_lic_stat \n";

   my $Secondary_lic_stat = $Rpc->get_system_variable("SecondaryLicenseFileStatus");
   print "Secondary_lic_stat $Secondary_lic_stat \n";

#   my $Started = $Rpc->get_system_variable("Started");
#   print "STARTED $Started \n";
   
   (my $IPAddress, my $IPMask, my $Dns, my $Gateway, my $Dhcp, my $Hostname) = $Rpc->get_system_net_info();
   print "IP: $IPAddress\n";
   print "Netmask: $IPMask\n";
   print "Gateway: $Gateway\n";
   print "DNS: $Dns\n";

