#!/usr/bin/perl -w
 
use FindBin;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_constants;
use orbital_rpc;
use Getopt::Std; 
#
# Initialization code
#
my $orb = "10.200.38.63" ;
getopt("o");
if ($opt_o) {$orb=$opt_o; chomp($orb)}
my $url = "http://$orb:2050/RPC2";
my $Rpc = Orbital::Rpc->new("http://$orb:2050/RPC2");
sleep 3;
print "Test started.\n";
   #
   # If there was an Alert, display it
   #
   my @Alert;
   my @NumAlerts=0;
   ($NumAlerts, @Alerts) = $Rpc->get_alerts();
      print("Displaying Alert!\n");
      print "There are: $NumAlerts Alerts \n";
      print" @Alerts \n";
 
   my $MaxAllowedThroughput = $Rpc->get_throughput();
   print "MAX THROUGHPUT: $MaxAllowedThroughput \n";
   my $IsPassthrough = $Rpc->get_parameter("PassThrough");
   print("PassThrough: $IsPassthrough\n");
   
   my $Version = $Rpc->get_system_variable("Version");
   print "VERSION $Version \n";

   my $Secondary_lic_stat = $Rpc->get_system_variable("SecondaryLicenseFileStatus");
   print "Secondary_lic_stat $Secondary_lic_stat \n";
 (my $IPAddress, my $IPMask, my $Dns, my $Gateway, my $Dhcp, my $Hostname) = $Rpc->get_system_net_info();
   print "IP: $IPAddress\n";
   print "Netmask: $IPMask\n";
   print "Gateway: $Gateway\n";
   print "DNS: $Dns\n";
#Test param set  
#   $Dns = '5.5.5.5';
#   $Rpc->set_system_net_info( $IPAddress, $IPMask,  $Dns,  $Gateway, $Dhcp,  $Hostname);
#Verify changes
#   print "EXPECT DNS to be $Dns /n";
# ($IPAddress, $IPMask, $Dns,  $Gateway,  $Dhcp,  $Hostname) = $Rpc->get_system_net_info();
#   print "IP: $IPAddress\n";
#   print "Netmask: $IPMask\n";
#   print "Gateway: $Gateway\n";
#   print "DNS: $Dns\n";


