#!/bin/sh
#Dong 3/25/05
#This script is used for reliability test.
if [ $# -ne 5 ]; then
   echo "usage $0 <IPERF Server> <#sess> <duration> <port> <dir>"
   exit 1
fi
sudo sh -c "ulimit -s 256 && ulimit -n 8192 && ulimit -a && /usr/local/bin/iperf -c $1 -P $2 -t $3 -p $4 -X $5 "

