#!/bin/bash
#
# Author:		Girish Narkhede
# Description:	Script to compare 2 directory trees using zipdiff
#
#
# $1	- path to generate log and tmp files in
# $2	- uvscanTree (master)
# $3	- virexTree
# $4	- LVT Scripts root
#
# The env vars
#	zipDiff	- Path of the zipdiff binary + assoc. env settings LD_PRELOAD etc
#
cmpTmp=$1
uvscanTree=$2
virexTree=$3
LVT_ROOT=$4

if [ -z ${zipdiff} ] ;    then zipdiff=${LVT_ROOT}/zipdiff ; fi


if [ -z "${uvscanTree}" -o ! -d "${uvscanTree}" ] ; then
    echo "missing uvscanTree"
    exit 1
fi

if [ -z "${virexTree}" -o ! -d "${virexTree}" ] ; then
    echo "missing virexTree"
    exit 1
fi

if [ -z "${zipdiff}" -o ! -x "${zipdiff}" ] ; then
    echo "missing zipdiff"
    exit 1
fi


rsts=0
echo "Comparing trees $virexTree and $uvscanTree"
echo
(
    # get list of relative files from nailsd
    ( cd ${virexTree} && find . -type f )

    # get list of relative files from uvscan
    ( cd ${uvscanTree} && find . -type f )
) | tee ${cmpTmp}.dircmp.raw | sort | uniq -u > ${cmpTmp}.dircmp.log

x=`wc -l < ${cmpTmp}.dircmp.log`
if [ $x != 0 ] ; then
    echo failed to compare directory contents see ${cmpTmp}.dircmp.log
    rsts=1
fi

( 
    csts=0
cd ${uvscanTree} ; find . -type f -print ) | ( \
    while read ndf ; do
	if [ -f "${uvscanTree}/${ndf}" ] ; then
	    if ! ${zipdiff} "${uvscanTree}/${ndf}" "${virexTree}/${ndf}" 2> "${uvscanTree}/${ndf}.zdlog" 1>&2 ; then
		#echo "zipdiff failure for ${uvscanTree} and ${virexTree} file ${ndf}"
		cat "${uvscanTree}/${ndf}.zdlog"
		echo
		csts=1
	    fi

	    # Move or delete the output from zipdiff to a different tree to prevent directory
	    # differences
	    if [ -s "${uvscanTree}/${ndf}.zdlog" ] ; then
		d=`dirname "${ndf}"`
		d="${cmpTmp}/zipdiff/${d}"
		if [ ! -d "${d}" ] ; then mkdir -p "${d}" ; fi
		mv "${uvscanTree}/${ndf}.zdlog" "${d}"
	    else
		rm "${uvscanTree}/${ndf}.zdlog"
	    fi

	fi
    done
    exit $csts
)
csts=$?
if [ $csts != 0 -o $rsts != 0 ] ; then
    exit 1
fi

exit 0
