// script generated by Xtreeme SiteXpert
// sitemap and search engine creator
// http://www.xtreeme.com/sitexpert
// Copyright(C) 2001-2002 Xtreeme GmbH

if (!document.loadHandlers)
{
	document.loadHandlers=new Array();
	document.loadHandlers[0]='initializeMenu';
	document.lastLoadHandler=0;
}
else
{
	document.lastLoadHandler++;
	document.loadHandlers[document.lastLoadHandler]='initializeMenu';
}
window.onload=initializeAll;

var activePopup=null;
var activePopupTimeout;
var maxZ=1000;
var popupFrame;
var targetFrame;
var docLoaded=false;
var bIncBorder=true;

function resetPopup(popup)
{
	if(popup&&popup.children)
	{
		var i;
		for(i=0;i<popup.children.length;i++)
		{
			if(popup.children[i].id.indexOf('sep')==-1)
			{
				popup.children[i].style.color=popup.normalColor;
				popup.children[i].style.backgroundColor=popup.normalBgColor;
			}
		}
	}
}

function buildPopup(arrayName,level)
{
	var levelAttribs;
	if (level > maxlev) {levelAttribs = eval ("lev" + maxlev) ;} else {levelAttribs = eval ("lev" + level) ;}
	var popupName=arrayName+"popup";
	popupFrame.document.write("<div id='"+popupName+"' style='position:absolute;padding-left:"+bord+";padding-top:"+bord+";padding-right:"+bord+";padding-bottom:"+bord+";visibility:hidden'>");

	var array=eval(arrayName);
	var arrayItem;
	var ali=" align='"+(popAlign==1?'center':(popAlign==2?'right':'left'))+"' ";
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		if (arrayItem>0&&sep)popupFrame.document.write("<div id='"+popupName+arrayItem+'sep'+"' style='background-color:"+borderCol+";height:"+sep+";width:"+(popupWidth-bord*2)+"'></div>");
		var popupArray=(array[arrayItem*3+2])?(arrayName+"_"+parseInt(arrayItem+1)):null;
		var iconTag=(array[arrayItem*3+2]?"<IMG SRC=\'"+(NS4?absPath:unescape(absPath))+imgFolder+"/sxicona.gif\' BORDER=0 WIDTH="+iconSize+" HEIGHT="+iconSize+" HSPACE=0 ALIGN=RIGHT>":"");
		var itemText=array[arrayItem*3];
		var style="width:"+(popupWidth-bord*2-vertSpace*2)+";padding-left:"+vertSpace+";padding-top:"+vertSpace+";padding-bottom:"+vertSpace;
		style+=";font-size:"+levelAttribs[0]+";width:"+(popupWidth-vertSpace*2-bord*2)+";color:"+levelAttribs[3]+";font-family:"+levelAttribs[6];
		if(levelAttribs[1])style+=";font-weight:bold";
		if(levelAttribs[2])style+=";font-style:italic";
		popupFrame.document.write("<div"+ali+"id='"+(popupName+arrayItem)+"' style=\""+style+"\">"+iconTag+itemText+"</div>");
	}
	popupFrame.document.write("<div style='height:0'>&nbsp;</div>");
	popupFrame.document.write("</div>");
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		if(array[arrayItem*3+2]) buildPopup(arrayName+'_'+(arrayItem+1),level+1);
	}
}

function findFrame(name)
{
	if(parent.frames[name])return parent.frames[name];
	var i;
	for(i=0;i<parent.frames.length;i++){if(parent.frames[i].frames[name])return parent.frames[i].frames[name];}
}

function buildPopups()
{
	popupFrame=(sepFrame&&!openSameFrame)?findFrame(contentFrame):window;
	targetFrame=(sepFrame)?findFrame(cntFrame):window;
	var i=1;
	while(true)
	{
		var menu=eval('mn'+i);
		if (!menu)break;
		buildPopup('mn'+i,0);
		i++;
	}
	popupFrame.document.close();
}

buildPopups ();

function createMenuItem(popup,id,itemLink,itemText,popupArray,levelAttribs,bLast,popupHeight)
{
	var itemWnd=popupFrame.document.getElementById(id);
	addEvent(itemWnd,"mouseover",onItemOver,false);
	addEvent(itemWnd,"mouseout",onItemOut,false);
	addEvent(itemWnd,"mousedown",onItemClick,false);
	addEvent(itemWnd,"dblclick",onItemClick,false);
	itemWnd.owner=popup;
	with (itemWnd.style)
	{
		if(itemLink){cursor="hand";}
		else{cursor="default";}
		backgroundColor=levelAttribs[4];
		setRealWidth(itemWnd,popupWidth,2*bord);
	}
	if (popupArray)itemWnd.popupArray=popupArray;
	if(itemLink&&itemLink.indexOf(':/')==-1&&itemLink.indexOf(':\\')==-1) itemWnd.url=unescape(absPath)+itemLink;
	else itemWnd.url=itemLink;
	itemWnd.dispText=itemText;
	if (0&&popupArray)
	{
		var expandArrow=popupFrame.document.createElement("IMG");
		itemWnd.appendChild(expandArrow);
		expandArrow.src=unescape(absPath)+imgFolder+"/sxicona.gif";
		with (expandArrow.style)
		{
			width=iconSize;
			height=iconSize;
			position="absolute";
			var itemRect=getClientRect(itemWnd);
			top=(itemRect.bottom-itemRect.top)/2-iconSize/2-2;
			left=itemWnd.offsetWidth-iconSize-1;
		}
	}
	return itemWnd.offsetHeight;
}

function setRealWidth(wnd,width,borderWidth)
{
	wnd.style.pixelWidth=width-borderWidth;
	if (wnd.style.pixelWidth>width-borderWidth) wnd.style.pixelWidth=width-parseInt(wnd.style.paddingLeft)-parseInt(wnd.style.paddingRight);
}

function createPopupFromCode(arrayName,level)
{
	var popupName=arrayName+"popup";
	var popup=popupFrame.document.getElementById(popupName);
	if (popup&&popup.bCreated)return popup;
	var levelAttribs;
	if (level > maxlev) {levelAttribs = eval ("lev" + maxlev) ;} else {levelAttribs = eval ("lev" + level) ;}

	popup.level=level;
	popup.highlightColor=levelAttribs[5];
	popup.normalColor=levelAttribs[3];
	popup.highlightBgColor=levelAttribs[7];
	popup.normalBgColor=levelAttribs[4];
	popup.scrVis=false;
	popup.bCreated=true;

	with (popup.style)
	{
		zIndex=maxZ;
		position="absolute";
		width=popupWidth;
		borderColor=borderCol;
		backgroundColor=bord?borderCol:levelAttribs[4];
		borderWidth=bord;
		borderStyle="solid";
	}

	addEvent(popup,"mouseout",onPopupOut,false);
	addEvent(popup,"mouseover",onPopupOver,false);
	var popupHeight=0;

	var array=eval(arrayName);
	var arrayItem;
	for(arrayItem=0;arrayItem<array.length/3;arrayItem++)
	{
		var popupArray=(array[arrayItem*3+2])?(arrayName+"_"+parseInt(arrayItem+1)):null;
		popupHeight+=createMenuItem(popup,(popupName+arrayItem),array[arrayItem*3+1],array[arrayItem*3],popupArray,levelAttribs,(arrayItem == array.length/3-1),popupHeight);
	}
	var bottomImgHeight=0;
	return popup;
}

function closePopup(popupId)
{
	if(popupId.indexOf('_')==-1){var hideWnd=popupFrame.document.getElementById('HideItem');if(hideWnd)hideWnd.style.visibility='visible';}
	var popup=popupFrame.document.getElementById(popupId);
	if (popup)
	{
		resetPopup(popup);
		if (popup.expandedWnd) closePopup (popup.expandedWnd.id);
		popup.style.visibility="hidden";
	}
	if (activePopup && activePopup.id==popupId) activePopup=null;
}

function absToRel(rect,refx,refy)
{
	var retval=new rct(rect.left-refx,rect.top-refy,rect.right-refx,rect.bottom-refy);
	return retval;
}

function openPopup(popup,x,y,bDontMove,refWnd)
{
	if(popup.id.indexOf('_')==-1){var hideWnd=popupFrame.document.getElementById('HideItem');if(hideWnd)hideWnd.style.visibility='hidden';}
	popup.style.pixelLeft=x;
	popup.style.pixelTop=y;
	popup.style.visibility="visible";
	var popupRect=getClientRect(popup);
	var browserRect=getBrowserRect(popupFrame);
	if (popupRect.right>browserRect.right)
	{
		if(refWnd.id&&refWnd.id.indexOf('top')==-1)popup.style.pixelLeft=Math.max(0,refWnd.offsetLeft-popup.offsetWidth+levelOffset);
		else popup.style.pixelLeft=browserRect.right-popup.offsetWidth-5;
	}
	//var cv=(bIncBorder?3:20);
	//if ((popupRect.bottom>browserRect.bottom))
	//{
	//	var newtop=browserRect.bottom-popup.offsetHeight-cv;
	//	popup.style.pixelTop=newtop;
	//}
}

function isChildOfActivePopup(popup)
{
	var wnd=activePopup;
	while(wnd)
	{
		if (wnd.id==popup.id)
			return true;
		wnd=wnd.expandedWnd;
	}
	return false;
}

function onPopupOver()
{
	if (activePopup && isChildOfActivePopup (this)) clearTimeout(activePopupTimeout);
}

function onPopupOut()
{
	onPopupOutImpl(this);
}

function onPopupOutImpl(popup)
{
	if (mout && activePopup && isChildOfActivePopup (popup))
	{
		if (activePopupTimeout) clearTimeout (activePopupTimeout);
		activePopupTimeout=setTimeout("closePopup('"+activePopup.id+"');", closeDelay);
	}
}

function rct(left,top,right,bottom)
{
	this.left=left;
	this.top=top;
	this.right=right;
	this.bottom=bottom;
}

function getBody(frame)
{
	var bodyArr=frame.document.getElementsByTagName('body');
	return bodyArr[0];
}

function getBrowserRect(doc)
{
	var body=getBody(doc);
	var left=body.style.pixelLeft;
	var top=body.style.pixelTop;
	var right=left+body.style.pixelWidth;
	var bottom=top+body.style.pixelHeight;
	var retval=new rct(left,top,right,bottom);
	return retval;	
}

function getClientRect(wnd)
{
	var left=0;
	var top=0;
	var right=0;
	var bottom=0;
	var par=wnd;
	while (par)
	{
		left+=par.offsetLeft;
		top+=par.offsetTop;
		if (par.offsetParent==par || par.offsetParent==getBody(popupFrame)) break;
		par=par.offsetParent;
	}
	right=left+wnd.offsetWidth;
	bottom=top+wnd.offsetHeight;
	var retval=new rct(left,top,right,bottom);
	return retval;
}

function onItemClick()
{
	var item=this;
	if (item.url)
	{
		var startPos=item.dispText.indexOf('<!--');
		if (startPos!=-1)
		{
			var endPos = item.dispText.indexOf('-->',startPos);
			var trgFrame = item.dispText.substring (startPos+4,endPos);
			if (trgFrame=="_blank") window.open (item.url);
			else eval("parent.frames."+trgFrame).location.href=item.url;
		}
		else
		{
			var find=item.url.indexOf("javascript:");
			if (find!=-1)
				eval(item.url.substring(find));
			else
				{
				var mt=item.url.indexOf("mailto:");
				if(mt!=-1)window.location=item.url.substring(mt);
				else if(popupFrame!=window) window.open(item.url);
				else targetFrame.location=item.url;
				}
		}
		if(activePopup)closePopup(activePopup.id);
	}
}

function onItemOver()
{
	var item=this;
	if (item.owner.expandedWnd)
	{
		resetPopup(item.owner);
		closePopup(item.owner.expandedWnd.id);
	}
	if (item.url&&item.url.indexOf("javascript:")==-1)
		window.status=item.url;
	else
		window.status="";
	item.style.color=item.owner.highlightColor;
	item.style.backgroundColor=item.owner.highlightBgColor;
	var items=item.owner.getElementsByTagName("DIV");
	if (item.popupArray)
	{
		var rect=getClientRect(item);
		var x=rect.right-levelOffset;
		var y=rect.top;
		var popup=createPopupFromCode(item.popupArray,item.owner.level+1);
		item.owner.expandedWnd=popup;
		openPopup(popup,x,y+2,false,item.owner);
	}
}

function onItemOut()
{
	var item=this;
	item.style.color=item.owner.normalColor;
	item.style.backgroundColor=item.owner.normalBgColor;
}

function expandMenu(popupId,refWnd,dum)
{
	if(!docLoaded)return;
	clearTimeout(activePopupTimeout);
	if (activePopup&&activePopup.id!=popupId+"popup")
		closePopup(activePopup.id);
	if(popupId=='none')return;
	var posRef=document.getElementById(refWnd);
	var rect=getClientRect(posRef);
	var x;
	var y;
	if(menuHorizontal)
	{
		x=rect.left;
		y=rect.bottom+popupOffset;
	}
	else
	{
		x=rect.right+popupOffset;
		y=rect.top;
	}
	if(sepFrame&&!openSameFrame)
	{
		var brRect=getBrowserRect(popupFrame);
		var wRect=getBrowserRect(window);
		switch (menuPos)
		{
		case 0:
			x=brRect.left;
			y+=brRect.top-wRect.top;
			break;
		case 1:
			x=brRect.right;
			y+=brRect.top-wRect.top;
			break;
		case 2:
			x+=brRect.left-wRect.left;
			y=brRect.top;
			break;
		case 3:
			x+=brRect.left-wRect.left;
			y=brRect.bottom;
			break;
		}
	}
	var popup=createPopupFromCode(popupId,0);
	openPopup(popup,x,y,true,posRef);
	activePopup=popup;
}

function collapseMenu(popupId)
{
	if(!docLoaded)return;
	var popup=popupFrame.document.getElementById(popupId+"popup");
	if(popup)onPopupOutImpl(popup);
}

function expandMenuNS(popupId,e,dItem)
{
}

function collapseMenuNS(popupId)
{
}

function onDocClick()
{
	if(activePopup)closePopup(activePopup.id);
}

function onDocClick()
{
	if(activePopup)closePopup(activePopup.id);
}

function initializeMenu()
{
	if(!mout)addEvent(popupFrame.document,"mousedown",onDocClick,false);
	docLoaded=true;
}

function addEvent(obj,event,fun,bubble)
{
	if (obj.addEventListener)
		obj.addEventListener(event,fun,bubble);
	else
		eval("obj.on"+event+"="+fun);
}

function chgBg(item,color)
{
	var el=document.getElementById(item);
	if (color==0)
	{
		if(!bBitmapScheme)el.style.background=tlmOrigBg;
		el.style.color=tlmOrigCol;
	}
	else
	{
		if(!bBitmapScheme&&(color&1))el.style.background=tlmHlBg ;
		if(color&2)el.style.color=tlmHlCol ;
	}
}

function initializeAll()
{
	var i;
	for(i=0;i<=document.lastLoadHandler;i++)
	{
		eval(document.loadHandlers[i]+'();');
	}
}