#!/tools/bin/perl
use lib '/tools/lib/perl5/site_perl/5.8.4';
use lib '/tools/tests/regression';
use Test::More qw(no_plan); 
use Time::localtime;
use XMLRPC::Lite;
use Getopt::Std;
use Data::Dumper;
use orbital_rpc;

my $testcase = "rel_apache";
#my $log_dir = "/var/tmp/";
my $log_dir = "\/logs\/TestResult\/"; #Logs for Dong's testbed
my $binfile = "ab_binfile";        #change these file as needed.
my $compfile = "ab_compfile";

my $maxbw_bps = 150000000;          #the remOrb must have this value before testing.
my $maxbw = 150;   
my $dr = '20.20.20.1';       #CNISTNET 
my $cnistnet = 1;            #Future use
my $rtt = 100;                      #default is 100 ms. Input overide.
my $loss = 0;
my $dr_dest = '0.0.0.0';
my $softboost = 0;		#default is HB for now


#------------------------------------
# -o: locOrb
# -r: remOrb
# -s: remHost
# -b: SB (opt) . The default is HB
# -m: email result (opt). The default is not senfing
#-----------------------------------
getopt ("o,r,s,b,m") ;
if ( !$opt_s || !$opt_o || !$opt_r) {
  print "\nUsage: $testcase.pl -o <locOrb> -r <remOrb> -s < HTTP Servers> | -b <1> | -m <1> \n\n";
  exit 1;
}
my $host =  $opt_s ; chomp ($host) ;
my $host_url= "http://" . $host ."/" ;

my $send_mail = 0;	#don't send email result as default
if ($opt_m) { $send_mail = $opt_m; chomp ($send_mail) }

#setup orbital parameters
my $locOrb = $opt_o; chomp ($locOrb);       #setup the Orb for XMLRPC
my $locOrb_url = "http://$locOrb:2050/RPC2";
my $locOrb_rpc = Orbital::Rpc->new($locOrb_url);

my $remOrb = $opt_r; chomp ($remOrb);       #setup the Orb for XMLRPC
my $remOrb_url = "http://$remOrb:2050/RPC2";
my $remOrb_rpc = Orbital::Rpc->new($remOrb_url);

if ($opt_b) { $softboost = $opt_b; chomp ($softboost) }

my $time=localtime;
$time = sprintf("%02d%02d%04d", $time->mday,($time->mon)+1, $time->year+1900);


#Find the Orb tested version
my $version = $locOrb_rpc->get_system_variable("Version");
my @version = split(/\s+/, $version);
my $i = 0; my $release ="";
while ($version[$i]) {
   if ($version[$i++] eq "Release") {
      $release = "$version[$i++]"."-";
      my $subver = int ($version[++$i]);
      $release = "$release"."$subver";}
}

#initialize the testbed
print LOG "Set the locOrb SendRate To $maxbw_bps \n", $locOrb_rpc->set_parameter('SlowSendRate', $maxbw_bps);
print LOG "Set the locOrb RecvRate To $maxbw_bps \n", $locOrb_rpc->set_parameter('SlowRecvRate', $maxbw_bps);
print LOG "Set the remOrb SendRate To $maxbw_bps \n", $remOrb_rpc->set_parameter('SlowSendRate', $maxbw_bps);
print LOG "Set the remOrb RecvRate To $maxbw_bps \n", $remOrb_rpc->set_parameter('SlowRecvRate', $maxbw_bps);
print LOG "\nSet locOrb To SoftBoost: ", $locOrb_rpc->set_parameter('UI.Softboost', $softboost);
print LOG "\nSet remOrb To SoftBoost: ", $remOrb_rpc->set_parameter('UI.Softboost', $softboost);

#curently, only CNISTNET is  used
if ($cnistnet) {
   config_CNISTNET ($dr, $dr_dest, $maxbw, $rtt, $loss);
   } else {
        config_TC ($dr, $maxbw, $rtt, $loss);
        }


#if the HTTP server is not running, start it.
my $HTTPD = `ssh $host "ps -e |grep httpd" `;
if (! $HTTPD) {print `ssh $host \"\/etc\/\init.d\/httpd start\"`;}

my $log_file = "$log_dir"."$testcase"."_$release"."_$time".".log";
open (LOG,  "> $log_file") || die "Could not open the file $log_file \n";

#print log header
printf LOG "\n%10s%10s\n%10s%10s\n%10s%10.0f\n",'Date:',$time,'Release:',$release,'SendRate:',$maxbw_bps;
print  LOG '*' x80, "\n\n";
print "URL:$host_url\n";

#---------Start AB with Compression OFF -------
print "Turn Compression OFF ", $locOrb_rpc->set_parameter('Compression.EnableCompression', '0'), "\n";
ok(ab(1,1,$host_url,$binfile,0) =~ /^Failed\W+requests:\W+0$/gxms,"AB : $binfile 1 request, 1 concurrent");
ok(ab(100,100,$host_url,$binfile,0) =~ /^Failed\W+requests:\W+0$/gxms,"AB : $binfile 100 requests, 100 concurrent");
ok(ab(300,300,$host_url,$binfile,0) =~ /^Failed\W+requests:\W+0$/gxms,"AB : $binfile 300 requests, 300 concurrent");

#---------Start AB with Compression ON -------
print "Turn Compression ON ", $locOrb_rpc->set_parameter('Compression.EnableCompression', '1'), "\n";
print "Turn Compression ON ", $remOrb_rpc->set_parameter('Compression.EnableCompression', '1'), "\n";
ok(ab(1,1,$host_url,$binfile,1) =~ /^Failed\W+requests:\W+0$/gxms,"AB COMPRESSION: $binfile 1 request, 1 concurrent");
ok(ab(100,100,$host_url,$binfile, 1) =~ /^Failed\W+requests:\W+0$/gxms,"AB COMPRESSION: $binfile 100 requests, 100 concurrent");
ok(ab(300,300,$host_url,$binfile, 1) =~ /^Failed\W+requests:\W+0$/gxms,"AB COMPRESSION: $binfile 300 requests, 300 concurrent");


#AB using compressible file
ok(ab(1,1,$host_url,$compfile,1) =~ /^Failed\W+requests:\W+0$/gxms,"AB COMPRESSION: $compfile 1 request, 1 concurrent");
ok(ab(10,10,$host_url,$compfile,1) =~ /^Failed\W+requests:\W+0$/gxms,"AB COMPRESSION: $compfile 100 requests, 100 concurrent");
ok(ab(100,100,$host_url,$compfile,1) =~ /^Failed\W+requests:\W+0$/gxms,"AB COMPRESSION: $compfile 300 requests, 300 concurrent");

#--------Stop AB with Compression ---------


#Change DR configuration back to its original configuration: 100RTT & 1% LOSS
config_TC ($dr, $maxbw, $rtt, $loss);
print "Reset SendRate To $maxbw_bps:", $locOrb_rpc->set_parameter('SlowSendRate',$maxbw_bps);


if ($send_mail) {
#   print `mail \-s \"ApacheBench Test Results of Release $rel\" engineering\@orbitaldata.com  \< $log_file`;
   print `mail \-s \"ApacheBench Test Results of Release $rel\" dong\@orbitaldata.com  \< $log_file`;
   }


#***********************************************************************
# format: ab (#connection, #concurrent, hostURL, file, compression (0/1)
#***********************************************************************
sub ab
{
  my $connections = shift ;
  my $concurrent = shift ;
  my $url = shift ;
  my $file = shift ;
  my $compression = shift;
  $url .= "/$file" ;
  
  my $ab  = `/tools/bin/ab -d -S -n $connections -c $concurrent $url`  ;
  if ($compression) {
     print LOG  "AB COMPRESSION TEST RESULT:\n$ab \n";
     print LOG  "------------------------------ \n\n";
     } else {
          print LOG  "AB TEST RESULT:\n$ab \n";
          print LOG  "------------------------------ \n\n";
          }
  return $ab ;
}

#*************************************************************************
sub config_CNISTNET
#Need 4 inputs: <DR IP> <REM-NETWORK> <BW Mbps> <RTT> <LOSS>
{
  print LOG "Configure CNISTNET DR: $_[0]\n";
  my $bw_Kbps = $_[2] * 1000;
  my $set_dr = "ssh $_[0] \".\/set_bw.sh $_[1] $bw_Kbps $_[3] $_[4]\" ";
  $set_dr = `$set_dr`;
  print LOG "Below is the CNISTNET DR configuration: \n $set_dr \n";
}

#************************************************************************
# This is for the Meshed Testbed DR
# /tools/test/test_common/neset.sh  -bw 100e6 -rtt 100 -loss 1
#Need 3 inputs: <DR IP> <BW Mbps> <RTT> <LOSS>
#------------------------------------------------------------------------
sub config_TC                                                                                                                      
{
  my $bw = "$_[1]"."e6";
  print LOG "Configure TC DR: $_[0]\n";
  my $set_dr = "ssh $_[0] \"\/tools\/tests\/test_common\/neset.sh \-bw $bw \-rtt $_[2] \-loss $_[3] \" ";
  print LOG "\nConfigure DR ...\n", `$set_dr`;
}

