/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Mytest6.xs. Do not edit this file, edit Mytest6.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Mytest6.xs"
#include <sys/vfs.h>
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


#line 19 "Mytest6.c"

XS(XS_Mytest6_multi_statfs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest6_multi_statfs)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mytest6::multi_statfs(paths)");
    {
	SV*	paths = ST(0);
	SV *	RETVAL;
#line 15 "Mytest6.xs"
	AV* results;
	I32 numpaths = 0;
	int i, n;
	struct statfs buf;
	if ((!SvROK(paths)) 
	|| (SvTYPE(SvRV(paths)) != SVt_PVAV)
	|| ((numpaths = av_len((AV *) SvRV(paths))) < 0)) {
	   XSRETURN_UNDEF;
	}
	results = (AV*) sv_2mortal((SV *)newAV());
#line 41 "Mytest6.c"
#line 26 "Mytest6.xs"
	for(n=0;n<=numpaths;n++) {
		HV * rh;
		STRLEN l;
		char * fn = SvPV(*av_fetch((AV *)SvRV(paths), n, 0), l);
		i = statfs(fn, &buf);
		if (i != 0) {
		    av_push(results, newSVnv(errno));
		    continue;
		}
		rh = (HV *)sv_2mortal((SV *)newHV());
		hv_store(rh, "f_bavail", 8, newSVnv(buf.f_bavail), 0);
		hv_store(rh, "f_bfree",  7, newSVnv(buf.f_bfree),  0);
		hv_store(rh, "f_blocks", 8, newSVnv(buf.f_blocks), 0);
		hv_store(rh, "f_bsize",  7, newSVnv(buf.f_bsize),  0);
		hv_store(rh, "f_ffree",  7, newSVnv(buf.f_ffree),  0);
		hv_store(rh, "f_files",  7, newSVnv(buf.f_files),  0);
		hv_store(rh, "f_type",   6, newSVnv(buf.f_type),   0);
		av_push(results, newRV((SV *)rh));
        }
        RETVAL = newRV((SV *)results);
#line 63 "Mytest6.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Mytest6); /* prototype to pass -Wmissing-prototypes */
XS(boot_Mytest6)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Mytest6::multi_statfs", XS_Mytest6_multi_statfs, file);
    XSRETURN_YES;
}

