#!/usr/bin/perl -w
package Orbital::Rpc; 
use FindBin;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_constants;
use orbital_rpc;
use Getopt::Std; 
#
# Initialization code
#
getopt("o");

if (!$opt_o) {
  print "Usage: $testcase  -o <OrbIP>  \n" ;
  exit 1 ;
}

my $orb=$opt_o; chomp($orb);
my $url = "http://$orb:2050/RPC2";
my $Rpc = Orbital::Rpc->new($url);

my $MaxAllowedThroughput = $Rpc->get_throughput();
   print "MAX THROUGHPUT: $MaxAllowedThroughput \n";

   my $IsPassthrough = $Rpc->get_parameter("PassThrough");
   print("PassThrough: $IsPassthrough\n");
   
#  $IsPassthrough = $Rpc->get_parameter("COMPRESSION.COMPUTECHECKSUM");
#   print("COMPRESSION.COMPUTECHECKSUM: $IsPassthrough\n");

   my $Version = $Rpc->get_system_variable("Version");
   print "VERSION-1 $Version \n";

   my $Primary_lic_stat = $Rpc->get_system_variable("PrimaryLicenseFileStatus");
   print "Pri_lic_stat $Primary_lic_stat \n";

   my $Secondary_lic_stat = $Rpc->get_system_variable("SecondaryLicenseFileStatus");
   print "Secondary_lic_stat $Secondary_lic_stat \n";

   my $Started = $Rpc->get_system_variable("Started");
   print "STARTED $Started \n";
   
   (my $IPAddress, my $IPMask, my $Dns, my $Gateway, my $Dhcp, my $Hostname) = $Rpc->get_system_net_info();

   print "IP: $IPAddress\n";
   print "Netmask: $IPMask\n";
   print "Gateway: $Gateway\n";
   print "DNS: $Dns\n";

