#!/usr/bin/perl -w
use strict;
use FindBin;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_constants;
use orbital_rpc;
 
#
# Initialization code
#
my $orb = "10.200.38.53" ;
#my $Rpc = Orbital::Rpc->new('http://10.200.38.53:2050/RPC2');
my $Rpc = Orbital::Rpc->new('http://localhost:2050/RPC2');
sleep 3;
print "Test started.\n";
   #
   # If there was an Alert, display it
   #

   my $Version = $Rpc->get_system_variable("Version");
   print "VERSION-1 $Version \n";


   my $Started = $Rpc->get_system_variable("Started");
   print "STARTED $Started \n";

   my $i = $Rpc->get_system_variable("HostName");
   print "HOST NAME $i \n";
#   $i = $Rpc->send_command ("reboot", "");         #Work
  $i=$Rpc->get_system_variable("Parameters");
  print "ALL PARAM $i \n";
