#!/usr/bin/perl -w
package Orbital::Rpc; 
use FindBin;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_constants;
use orbital_rpc;
use Getopt::Std; 
#
# Initialization code
#
getopt("o");

if (!$opt_o) {
  print "Usage: $testcase  -o <OrbIP>  \n" ;
  exit 1 ;
}

my $orb=$opt_o; chomp($orb);
my $url = "http://$orb:2050/RPC2";
my $Rpc = Orbital::Rpc->new($url);

my $logfile = "/tmp/vmstat.log";
open (LOG, ">$logfile") || die "Could not open the file $logfile \n";

   print LOG "Orbital ...$orb \n";
   my $Version = $Rpc->get_system_variable("Version");
   print LOG "Version ... $Version \n";


#   my $Started = $Rpc->get_system_variable("System.VMUsage");
#   print "VMUsage", Dumper ($Started) ;

   print LOG "\nMEMSTAT \n", $Rpc->send_command("mem.stat");
   print LOG "\n------------------------------------------\n";

   

