#!/tools/bin/perl

use lib '/tools/lib/perl5/site_perl/5.8.4';
use lib '/tools/tests/regression';
use Test::More  qw(no_plan); 
use Carp ;
use Getopt::Std ;
use Net::RawIP qw ( :pcap) ;
use XMLRPC::Lite;
use Data::Dumper;
use orbital_rpc;

my $testcase="try";
getopt ("o") ;

if (! $opt_o) {
  print "Usage: $testcase  -o <OrbIP>  \n" ;
  exit 1 ;
}
my $orb = $opt_o; chomp ($orb);       #setup the Orb for XMLRPC
my $url = "http://$orb:2050/RPC2";
my $rpc = Orbital::Rpc->new($url);
my $ver = &orb_version($rpc);
print "\nVERSION OF THE ORBITAL $orb is $ver \n";

#my $version = $rpc->get_system_variable("Version");
#print "\nVERSION OF THE ORBITAL $orb is $version \n";

#----------------------------------------------------
# Find the running Orb version
# input: $locOrb_rpc or $remOrb_rpc
#----------------------------------------------------
sub orb_version
{
    my $orb_rpc = shift;
    my $ver = $orb_rpc->get_system_variable("Version");
    my @ver = split(/\s+/, $ver);
    my $i = 0; my $rel ="";
    while ($ver[$i]) {
       if ($ver[$i++] eq "Release") {
          $rel = "$ver[$i++]"."-";
          my $subver = int ($ver[++$i]);
          $rel = "$rel"."$subver";
        }
    }
    return $rel;
}

