#!/tools/bin/perl
use lib '/tools/lib/perl5/site_perl/5.8.4';
use lib '/tools/tests/regression';
use Test::More qw(no_plan); 
use Time::localtime;
use XMLRPC::Lite;
use Getopt::Std;
use Data::Dumper;
use orbital_rpc;

my $config_file = "memstat.cfg";

getopt ("f") ;
if ( $opt_f) {
  $config_file = $opt_f; chomp ($config_file);
}


#The mem.stat info will be saved in /tmp/memstat.log
my $logfile = "/tmp/memstat.log";
open (LOG, ">$logfile") || die "Could not open the file $logfile \n";

#Open the memstat.cfg file - contains the Orb to be monitored
open (PARM,  "< $config_file") || die "Could not open the file $config_file \n";

while 1 {

while (<PARM>) {
   if (! (/#/)) {           #skip comment lines
      my $orb=$_;chomp($orb);

      my $url = "http://$orb:2050/RPC2";
      my $Rpc = Orbital::Rpc->new($url);
 
 
      print LOG "Orbital ...$orb \n";
      my $Version = $Rpc->get_system_variable("Version");
      printf  LOG "Version ...%-40s\n", $Version ;
 
 
      print LOG "\nMEMSTAT \n", $Rpc->send_command("mem.stat");
      print LOG "\n------------------------------------------\n";
 
     }
}

sleep 300;
print LOG "\n**********************************************\n";
}













