/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Mytest3.xs. Do not edit this file, edit Mytest3.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Mytest3.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


#line 18 "Mytest3.c"

XS(XS_Mytest3_round); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest3_round)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mytest3::round(arg)");
    {
	double	arg = (double)SvNV(ST(0));
#line 14 "Mytest3.xs"
	if(arg > 0.0) {
	       arg = floor(arg+0.5);
	} else if (arg < 0.0) {
	       arg = ceil(arg - 0.5);
	} else {
	       arg = 0.0;
	}
#line 36 "Mytest3.c"
	sv_setnv(ST(0), (double)arg);
	SvSETMAGIC(ST(0));
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Mytest3); /* prototype to pass -Wmissing-prototypes */
XS(boot_Mytest3)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Mytest3::round", XS_Mytest3_round, file);
    XSRETURN_YES;
}

