#!/tools/bin/perl

=head1 NAME


=head1 SYNOPSIS


=head1 DESCRIPTION

=head2 Overview

=head2 Test Category

=head1 ENVIRONMENT


=head1 BUGS

=head1 FILES

=head1 Authors

Dong Duong 

=head1 COPYRIGHT


=cut 


#use Test::More  qw(no_plan); # the number of tests
use Test::More  tests => 1 ;  
use Carp ;
use Getopt::Std ;
use Net::RawIP qw ( :pcap) ;


getopt ("s") ;
if (  ! $opt_s  ) {
  print "Usage: testcase_number -s <ip address>  \n" ;
  exit 1 ;
}
my $host = $opt_s;
chomp ($host );

is(nemesis_scan($host , " -S $client  " ) , 1, "NEMESIS ip: simple packet") ;

#foreach my $t ( 1 .. 127 ) {
#  is(nemesis_scan($host , " -S $client -p $t") , 1, "NEMESIS ip: simple packet, Protocol number : $t" ) ;
#}

sub nemesis_scan
  {
    my $host = shift ;
    my $args = shift ;
    my $invoke = "/tools/bin/nemesis ip  $args -D $host -v" ;
    my $ip = `$invoke` ;
    my $ping  = `ping -c 1 $host ` ;
    if ( ( $ip =~ /.*Wrote.*/gxms) && ( $ping =~/.*1\W+received.*/gxms)  ) {
      return 1 ;
    } else { return  0 ; }
  }

