#!/usr/bin/perl -w

open(out0, " >/etc/squid/principal/content");#to open file&append #information
close(out0); #closing of a file
open(out1, " >/etc/squid/principal/domainname");
close(out1);
open(out2, " >/etc/squid/principal/match");
close(out2);
open(out3, " >/etc/squid/principal/ports");
close(out3);
open(out4, " >/etc/squid/principal/ip");
close(out4);
open(out5, " >/etc/squid/hods/content");
close(out5);
open(out6, " >/etc/squid/hods/domainname");
close(out6);
open(out7, " >/etc/squid/hods/match");
close(out7);
open(out8, " >/etc/squid/hods/ports");
close(out8);
open(out9, " >/etc/squid/hods/ip");
close(out9);
open(ou0, " >/etc/squid/ecelan/content");
close(ou0);
open(ou0, " >/etc/squid/ecelan/domainname");
close(ou0);
open(ou1, " >/etc/squid/ecelan/match");
close(ou1);
open(ou2, " >/etc/squid/ecelan/ports");
close(ou2);
open(ou3, " >/etc/squid/ecelan/ip");
close(ou3);
open(a1, " >/etc/squid/eeelan/content");
close(a1);
open(a2, " >/etc/squid/eeelan/domainname");
close(a2);
open(a3, " >/etc/squid/eeelan/match");
close(a3);
open(a4, " >/etc/squid/eeelan/ports");
close(a4);
open(a5, " >/etc/squid/eeelan/ip");
close(a5);
open(ou4, " >/etc/squid/cselan/content");
close(ou4);
open(ou5, " >/etc/squid/cselan/domainname");
close(ou5);
open(ou6, " >/etc/squid/cselan/match");
close(ou6);
open(ou7, " >/etc/squid/cselan/ports");
close(ou7);
open(ou8, " >/etc/squid/cselan/ip");
close(ou8);
open(ou9, " >/etc/squid/itlan/content");
close(ou9);
open(ou11, " >/etc/squid/itlan/domainname");
close(ou11);
open(ou22, " >/etc/squid/itlan/match");
close(ou22);
open(ou33, " >/etc/squid/itlan/ports");
close(ou33);
open(ou44, " >/etc/squid/itlan/ip");
close(ou44);
open(ou55, " >/etc/squid/mechlan/content");
close(ou55);
open(ou66, " >/etc/squid/mechlan/domainname");
close(ou66);
open(ou77, " >/etc/squid/mechlan/match");
close(ou77);
open(ou88, " >/etc/squid/mechlan/ports");
close(ou88);
open(ou99, " >/etc/squid/mechlan/ip");
close(ou99);
open(ou12, " >/etc/squid/chemlan/content");
close(ou12);
open(ou13, " >/etc/squid/chemlan/domainname");
close(ou13);
open(ou14, " >/etc/squid/chemlan/match");
close(ou14);
open(ou15, " >/etc/squid/chemlan/ports");
close(ou15);
open(ou16, " >/etc/squid/chemlan/ip");
close(ou16);
print "Content-Type:text/html \n\n";# header information
print"ok";