logman start mcshell
logman start mchost
logman start mcagent
logman start mcmscsvc
logman start mcuimgr
logman start mcupdmgr
logman start mpfsrv
logman start mpsalert
logman start mcproxy
logman start msksrver
logman start mcshield
logman start mcsysmon
logman start mcvsshld
logman start mcods
logman start mcNAsvc
logman start mcAfeeDataBackup
logman start mBackMonitor
logman start mcSACore
logman start mcinsupd