logman stop mcshell
logman stop mchost
logman stop mcagent
logman stop mcmscsvc
logman stop mcuimgr
logman stop mcupdmgr
logman stop mpfsrv
logman stop mpsalert
logman stop mcproxy
logman stop msksrver
logman stop mcshield
logman stop mcsysmon
logman stop mcvsshld
logman stop mcods
logman stop mcNAsvc
logman stop mcAfeeDataBackup
logman stop mBackMonitor
logman stop mcSACore
logman stop mcinsupd