CREATE TABLE USER (
    USERID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
	PHONE VARCHAR(14) NOT NULL,
	STREET1 VARCHAR(40) NOT NULL,
	STREET2 VARCHAR(30),
	AREA VARCHAR(30) NOT NULL,
	CITY VARCHAR(30) NOT NULL,
	STATE VARCHAR(40) NOT NULL,
	PRIMARY KEY(USERID)
);

CREATE TABLE ACCOUNT (
    ID INT NOT NULL,
    BALANCE INT NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TRANSACTION {
    ID INT NOT NULL AUTO_INCREMENT,
    USERID INT NOT NULL,
    PREV_BALANCE INT NOT NULL,
    BALANCE INT NOT NULL,
    TRANS_TYPE INT NOT NULL,
    DESCRIPTION VARCHAR(150) NOT NULL,
    TRANS_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
}

CREATE TABLE CUISINE (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
	PRICE INT NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE SUBSCRIPTION (
    ID INT NOT NULL AUTO_INCREMENT,
    USERID INT NOT NULL,
    CUISINEID INT NOT NULL,
	ACTIVE INT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE DELIVERY (
    ID INT NOT NULL AUTO_INCREMENT,
    SUBID INT NOT NULL,
    TRANSACTION_ID INT NOT NULL,
	PRIMARY KEY (ID)
);

